#!/usr/bin/env bash

set -euo pipefail

cargo_dir="$(realpath "$(dirname "$0")")/.."
cd "$cargo_dir"

export RUST_BACKTRACE=1
exec cargo run -- --intercept-io="intercept/test" --workspace="tests/fixtures/main_lib" -vv
