---
name: CI

# yamllint disable-line rule:truthy
on:
  merge_group:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: yamllint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c  # v3.1.1
        with:
          strict: true
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: Install Toolchain
        uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b  # master
        with:
          components: clippy, rust-analyzer, rustfmt
          toolchain: stable

      - name: Cache
        uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0  # v2.8.0

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - name: cargo check
        run: cargo check --workspace --all-features

      - name: cargo build
        run: cargo build --workspace --all-features

      - name: cargo clippy
        run: cargo clippy --all-features --all-targets --workspace -- -D warnings

      - name: cargo test
        run: cargo test --all-features --workspace
        env:
          TEST_IO_INTERCEPT: intercept

      - name: cargo doc
        run: cargo doc --document-private-items --no-deps --all-features --workspace

      - name: cargo bench
        run: cargo bench --profile=dev --all-features --workspace -- --test

      - name: upload logs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        if: always()
        with:
          name: IO interception
          path: intercept
